const mongoose = require("mongoose");

const rideSchema = new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user",
        required:true
    },
    driverId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"driver",
        required:false
    },
    source:{
        type:String,
        required:true
    },
    destination:{
        type:String,
        required:true
    },
    distance:{
        type:String,
        required:true
    },
    time:{
        type:String,
        required:true
    },
    serviceType:{
        type:String,
        required:true
    },
    paymentMethod:{
        type:String,
        required:true
    },
    rideTime:{
        type:Date,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    driverProfit:{
        type:Number,
        required:true
    },
    stops:{
        type:[String],
        required:true
    },
    userName:{
        type:String,
        required:true
    },
    userEmail:{
        type:String,
        required:true
    },
    userPhone:{
        type:String,
        required:true
    },
    rideId:{
        type:String,
        required:true,
        unique:true
    },
    status:{
        type:String,
        required:true,
        default:"available"
    },
    rideType:{
        type:String,
        required:true
    },
    endPoints:{
        type:[Object],
        required:true
    },
    stopPoints:{
        type:[Object],
        required:true
    },
    sourceCity:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"zone",
        required:true
    },
    blockList:{
        type:[String],
        ref:"driver",
        required:false,
        default:[]
    },
    timeOfAssign:{
        type:Date,
        required:false
    },
    AcceptanceStatus:{
        type:Number,
        required:false,
    },
    rating:{
        type:Number,
        required:true,
        default:0
    }
})

module.exports = mongoose.model("ride", rideSchema)